### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by budpi** [mholgatem/ThermOS#13]
Linux ThermoPi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Dec  7 07:26:34 2017
pi@ThermoPi:~ $ cd ~
pi@ThermoPi:~ $ git clone https://github.com/mholgatem/ThermOS
fatal: destination path 'ThermOS' already exists and is not an empty directory.
pi@ThermoPi:~ $ cd ~/ThermOS
pi@ThermoPi:~/ThermOS $ sudo bash install.sh
Running Update...
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Get:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease [15.0 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages [11.7 MB]
Fetched 11.7 MB in 28s (407 kB/s)
Reading package lists... Done

Installing Dependencies...

Reading package lists... Done
Building dependency tree
Reading state information... Done
nginx is already the newest version (1.10.3-1+deb9u1).
python-dev is already the newest version (2.7.13-2).
sqlite3 is already the newest version (3.16.2-5).
python-pip is already the newest version (9.0.1-2+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages
Collecting gunicorn
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Collecting pygal
  Using cached pygal-2.4.0-py2.py3-none-any.whl
Collecting python-forecastio
  Using cached python-forecastio-1.3.5.tar.gz
Requirement already satisfied: requests>=1.6 in /usr/lib/python2.7/dist-packages (from python-forecastio)
Collecting responses (from python-forecastio)
  Using cached responses-0.8.1-py2.py3-none-any.whl
Collecting cookies (from responses->python-forecastio)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
ln: failed to create symbolic link '/etc/nginx/sites-enabled/ThermOS': File exists
rm: cannot remove '/etc/nginx/sites-enabled/default': No such file or directory
Error: duplicate column name: uvIndex

-----------------
Installation Complete!
Type your Pi's IP address into a web browser to access your control panel
192.168.1.40
-----------------
pi@ThermoPi:~/ThermOS $

**Comment by mholgatem** [comment]
from what you posted, it looks like you already had it installed. what happens when you try accessing the web frontend?

**Comment by budpi** [comment]
502 BAD GATEWAY

**Comment by budpi** [comment]
Linux ThermoPi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Dec  7 21:33:25 2017
pi@ThermoPi:~ $ sudo systemctl stop thermostat-web
pi@ThermoPi:~ $ cd ~/ThermOS
pi@ThermoPi:~/ThermOS $ sudo python thermostat_web.py
Traceback (most recent call last):
  File "thermostat_web.py", line 8, in <module>
    import pygal
ImportError: No module named pygal
pi@ThermoPi:~/ThermOS $

**Comment by mholgatem** [comment]
try doing this:
`sudo pip install pygal`
then try
`sudo python thermostat_web.py`
See if that fixes it

**Comment by budpi** [comment]
I re-flashed and started over. The install was a success the second time around. Since you've update to nginx it seems faster, especially since I am down to just one ds18b20 instead of the 5 as I had original planned. But as far as the furnace hook up goes...i thought it was a fairly easy task but I must be missing something. I'm thinking I am gonna have to give up on this protect. Thanks for all your hard work and fast response time.

**Comment by mholgatem** [comment]
sorry to hear that. let me know if there is anything else I can do to help.
