### ISSUE TITLE
Error when trying to setup a Schedule

### ISSUE THREAD

**Issue by theotherguy2175** [mholgatem/ThermOS#18]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
![capture](https://user-images.githubusercontent.com/6321643/41948929-1e2e42a8-798d-11e8-86df-c8d713c70189.PNG)

**Comment by mholgatem** [comment]
do this in unix console:

cd ~/ThermOS
/usr/local/bin/gunicorn thermostat_web:app -b 0.0.0.0:8080

navigate to 

> your.ThermOS.ip.address:8080

click on schedule. If you still get the error, copy and paste the output from the unix console.

**Comment by theotherguy2175** [comment]
/usr/local/bin/gunicorn thermostat_web:app -b 0.0.0.0:8080
[2018-06-30 14:01:31 +0000] [18651] [INFO] Starting gunicorn 19.8.1
[2018-06-30 14:01:31 +0000] [18651] [INFO] Listening at: http://0.0.0.0:8080 (18651)
[2018-06-30 14:01:31 +0000] [18651] [INFO] Using worker: sync
[2018-06-30 14:01:31 +0000] [18656] [INFO] Booting worker with pid: 18656
^C[2018-06-30 15:29:55 +0000] [18651] [INFO] Handling signal: int
[2018-06-30 15:29:55 +0000] [18656] [INFO] Worker exiting (pid: 18656)
[2018-06-30 15:29:55 +0000] [18651] [INFO] Shutting down: Master

**Comment by mholgatem** [comment]
sorry, my mistake. I forgot that gunicorn doesn't output the debug information without some edits. do this instead:

```
cd ~/ThermOS
sudo service nginx stop
sudo python thermostat_web.py
```

navigate to the thermostat like normal (without the :8080) and it should output any errors encountered.

**Comment by theotherguy2175** [comment]
This was the output i got. THank you for your help!


pi@raspberrypi:~/ThermOS $ sudo python thermostat_web.py

 * Running on http://0.0.0.0:80/
 * Restarting with reloader
192.168.0.108 - - [01/Jul/2018 01:06:10] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:14] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.106 - - [01/Jul/2018 01:06:14] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.106 - - [01/Jul/2018 01:06:15] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:19] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.106 - - [01/Jul/2018 01:06:20] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:22] "GET /schedule HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:22] "GET /static/css/bootstrap.css HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:22] "GET /static/css/main.css HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:22] "GET /static/css/bootstrap-datetimepicker.min.css HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/bootstrap-datetimepicker.min.js HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/jquery.min.js HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/bootstrap.min.js HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/fonts/AGENCYR.woff HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/fonts/AGENCYB.woff HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:23] "GET /static/images/bg.png HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /schedule/edit?id=new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/share/pyshared/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pyshared/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/pyshared/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/pyshared/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/ThermOS/thermostat_web.py", line 350, in schedule_edit
    return render_template("schedule_edit_form.html", entry=entry)
  File "/usr/share/pyshared/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/ThermOS/templates/schedule_edit_form.html", line 92, in template
    <option value="{{ option }}" {% if option is equalto (entry.date) %}selected{% endif %}>{{ option }}</option>
TemplateAssertionError: no test named 'equalto'
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:24] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:25] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:29] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:34] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 01:06:36] "GET /_liveUpdate HTTP/1.1" 200 -

**Comment by mholgatem** [comment]
ok, let's see what version of Jinja2 that you have.

`pip show Jinja2`

**Comment by mholgatem** [comment]
ah, that's the problem. it's an old version of jinja.

this should fix the problem.

`pip install --upgrade Jinja2`

**Comment by theotherguy2175** [comment]
When trying to perform the update this is the error I revived

pi@raspberrypi:~ $ pip install --upgrade Jinja2
Downloading/unpacking Jinja2 from https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl#sha256=74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB): 126kB downloaded
Downloading/unpacking MarkupSafe>=0.23 from https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from Jinja2)
  Downloading MarkupSafe-1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-yReKKv/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Installing collected packages: Jinja2, MarkupSafe
  Found existing installation: Jinja2 2.7.3
    Not uninstalling Jinja2 at /usr/lib/python2.7/dist-packages, owned by OS
Compiling /tmp/pip-build-yReKKv/Jinja2/jinja2/asyncfilters.py ...
  File "/tmp/pip-build-yReKKv/Jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-yReKKv/Jinja2/jinja2/asyncsupport.py ...
  File "/tmp/pip-build-yReKKv/Jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

  Can't roll back Jinja2; was not uninstalled
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/Jinja2-2.10.dist-info'

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by theotherguy2175** [comment]
Ok, so nevermind i just had to run that previous command with sudo and it upgraded. Sadly its still giving the same error when trying to add an entry into the schedule.

**Comment by mholgatem** [comment]
that's really weird. After running it like this:

```
cd ~/ThermOS
sudo service nginx stop
sudo python thermostat_web.py
```
is it still spitting out the 
`TemplateAssertionError: no test named 'equalto'` error?

if so, do this
```
python
import jinja2
jinja2.__version__
*note: there are two underscores on each side of 'version'
(ctrl + z to stop the python console)
```

**Comment by theotherguy2175** [comment]
this is the python log

pi@raspberrypi:~/ThermOS $ sudo python thermostat_web.py
 * Running on http://0.0.0.0:80/
 * Restarting with reloader
192.168.0.108 - - [01/Jul/2018 21:48:27] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:32] "GET /schedule HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:32] "GET /_liveUpdate HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:32] "GET /static/css/bootstrap-datetimepicker.min.css HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 21:48:32] "GET /static/bootstrap-datetimepicker.min.js HTTP/1.1" 304 -
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?id=new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/share/pyshared/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pyshared/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/pyshared/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/pyshared/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/ThermOS/thermostat_web.py", line 350, in schedule_edit
    return render_template("schedule_edit_form.html", entry=entry)
  File "/usr/share/pyshared/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/ThermOS/templates/schedule_edit_form.html", line 92, in template
    <option value="{{ option }}" {% if option is equalto (entry.date) %}selected{% endif %}>{{ option }}</option>
TemplateAssertionError: no test named 'equalto'
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:35] "GET /schedule/edit?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
192.168.0.108 - - [01/Jul/2018 21:48:37] "GET /_liveUpdate HTTP/1.1" 200 -
^Z
[1]+  Stopped                 sudo python thermostat_web.py

**Comment by theotherguy2175** [comment]
And the Jinja2 version is 2.7.3

**Comment by mholgatem** [comment]
ok, so jinja didn't actually update. lets just fully uninstall it, then re-install it.

sudo pip uninstall Jinja2 -y
sudo pip install Jinja2==2.10

You will probably get a couple of syntax errors, but it should install successfully.

**Comment by theotherguy2175** [comment]
So I was able to uninstall Jinja to the latest version but now its doing the famous 

502 Bad Gateway
nginx/1.6.2

**Comment by theotherguy2175** [comment]
FIXED IT, after rebooting and installing thermos again. It is successfully taking the schedule now. Thank you!

This is an amazing setup and i appreciate the quick responses. You make doing fun hobbies like this enjoyable!

**Comment by mholgatem** [comment]
cool. Glad you got it working. Let me know if you run into any other problems!
